# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='postion',
            new_name='position',
        ),
    ]
